apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webservi
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webservi
                port: 
                  number: {{ .Values.service.port }}

